### ISSUE TITLE
node will panic when running simple undo testcase

### ISSUE THREAD

**Issue by whunmr** [copernet/copernicus#155]
**Describe the bug**
when running testcase for undo, the node will panic.

**To Reproduce**
1. running testcase [single_node_undo.py](https://github.com/copernet/walle/blob/master/single_node_undo.py)
```
pipenv run python single_node_undo.py --tracerpc -l DEBUG --nocleanup
```

**Expected behavior**
undo successfully and no panic

**Additional context**
panic logs:
```
2018-10-18 12:50:29.269000 TestFramework (INFO): height 101, hash: 12158721378675693663521002650064272439080797260410274965317733538595202393199
2018-10-18 12:50:29.269000 TestFramework (INFO): #5. expect node0 switch to new chain
panic: newcoin fresh and oldcoin has spent

goroutine 148 [running]:
github.com/copernet/copernicus/model/utxo.(*CoinsLruCache).UpdateCoins(0xc000196080, 0xc0001d2520, 0xc000744800, 0x0, 0x0)
	/Users/bj1809120051/.go/src/github.com/copernet/copernicus/model/utxo/lrucache.go:125 +0x863
github.com/copernet/copernicus/logic/lchain.ConnectTip(0xc000f0f600, 0xc0001fa000, 0xc000ecb1a0, 0x0, 0x0)
	/Users/bj1809120051/.go/src/github.com/copernet/copernicus/logic/lchain/lchain.go:256 +0x7f6
github.com/copernet/copernicus/logic/lchain.ActivateBestChainStep(0xc000f0f600, 0xc0001fa000, 0xc000ecb0e6, 0xc000ecb1a0, 0x0, 0x0)
	/Users/bj1809120051/.go/src/github.com/copernet/copernicus/logic/lchain/lactivechain.go:155 +0x404
github.com/copernet/copernicus/logic/lchain.ActivateBestChain(0xc0001fa000, 0x0, 0x0)
	/Users/bj1809120051/.go/src/github.com/copernet/copernicus/logic/lchain/lactivechain.go:71 +0x2d5
github.com/copernet/copernicus/service.ProcessNewBlock(0xc0001fa000, 0x4a88301, 0xc000ecb4d3, 0x0, 0x0)
	/Users/bj1809120051/.go/src/github.com/copernet/copernicus/service/blockservice.go:89 +0x5ef
github.com/copernet/copernicus/service.ProcessBlock(0xc0001fa000, 0xc0002e3e00, 0x0, 0x0)
	/Users/bj1809120051/.go/src/github.com/copernet/copernicus/service/blockservice.go:43 +0x36e
github.com/copernet/copernicus/net/syncmanager.(*SyncManager).handleBlockMsg(0xc00019a0c0, 0xc000e321e0)
	/Users/bj1809120051/.go/src/github.com/copernet/copernicus/net/syncmanager/syncmanager.go:607 +0x333
github.com/copernet/copernicus/net/syncmanager.(*SyncManager).messagesHandler(0xc00019a0c0)
	/Users/bj1809120051/.go/src/github.com/copernet/copernicus/net/syncmanager/syncmanager.go:1179 +0x67f
created by github.com/copernet/copernicus/net/syncmanager.(*SyncManager).Start
	/Users/bj1809120051/.go/src/github.com/copernet/copernicus/net/syncmanager/syncmanager.go:1426 +0xb8
2018-10-18 12:50:29.366000 TestFramework.mininode (DEBUG): Closing connection to: 127.0.0.1:12864
2018-10-18 12:50:29.366000 TestFramework.mininode (DEBUG): Closing connection to: 127.0.0.1:12864
2018-10-18 12:50:29.366000 TestFramework.mininode (DEBUG): Network thread closing
```

**Comment by whunmr** [comment]
solved by commit https://github.com/copernet/copernicus/commit/bb501228fe437027ec15beefdd7736655d4bdf65
