### ISSUE TITLE
unittest in ./check.sh failed, when there is a Copernicus running on localhost

### ISSUE THREAD

**Issue by whunmr** [copernet/copernicus#212]
**Describe the bug**
unittest in ./check.sh failed, when there is a copernicus is running on localhost

**To Reproduce**
1.  start a copernicus instance on localhost with default mainnet parameter
2. running ./check.sh

**Additional context**
```
| => ./check.sh 2>&1 | grep -v "ld: warning: text-based stub file"
++ type -p glide
+ '[' '!' -x /usr/local/bin/glide ']'
++ type -p gometalinter
+ '[' '!' -x /Users/bj1809120051/.go/bin/gometalinter ']'
+ find . -name '*.go' -not -path './vendor/*' -not -path './git/*'
+ xargs gofmt -w
++ glide novendor
+ linter_targets='./crypto/...
./tools/...
./net/...
./util/...
./logic/...
./peer/...
./model/...
./log/...
./service/...
./rpc/...
./conf/...
./persist/...
./errcode/...
.'
++ gometalinter -j 4 --disable-all --enable=gofmt --enable=golint --enable=gosimple --enable=ineffassign --enable=vet --enable=misspell --enable=unconvert '--exclude=should have comment' '--exclude=and that stutters;' --deadline=10m ./crypto/... ./tools/... ./net/... ./util/... ./logic/... ./peer/... ./model/... ./log/... ./service/... ./rpc/... ./conf/... ./persist/... ./errcode/... .
++ grep -v 'ALL_CAPS\|OP_'
++ tee /dev/stderr
+ test -z ''
+ go test -covermode=atomic -coverprofile=coverage.out -race -tags rpctest ./crypto/... ./tools/... ./net/... ./util/... ./logic/... ./peer/... ./model/... ./log/... ./service/... ./rpc/... ./conf/... ./persist/... ./errcode/... .
# github.com/copernet/copernicus/logic/lmerkleroot.test
# github.com/copernet/copernicus/model/txin.test
# github.com/copernet/copernicus/crypto.test
# github.com/copernet/copernicus/net/addrmgr.test
# github.com/copernet/copernicus/model/script.test
# github.com/copernet/copernicus/net/connmgr.test
# github.com/copernet/copernicus/util/cashaddr.test
# github.com/copernet/copernicus/util/bloom.test
# github.com/copernet/copernicus/util/wif.test
# github.com/copernet/copernicus/net/syncmanager.test
# github.com/copernet/copernicus/net/wire.test
# github.com/copernet/copernicus/logic/lblock.test
# github.com/copernet/copernicus/net/server.test
# github.com/copernet/copernicus/logic/lblockindex.test
ok  	github.com/copernet/copernicus/crypto	10.080s	coverage: 77.1% of statements
?   	github.com/copernet/copernicus/tools/blockanalyse	[no test files]
?   	github.com/copernet/copernicus/tools/coperctl	[no test files]
# github.com/copernet/copernicus/logic/lchain.test
# github.com/copernet/copernicus/logic/lmempool.test
# github.com/copernet/copernicus/logic/lmerkleblock.test
# github.com/copernet/copernicus/logic/lscript.test
# github.com/copernet/copernicus/logic/lreindex.test
ok  	github.com/copernet/copernicus/net/addrmgr	20.027s	coverage: 83.5% of statements
ok  	github.com/copernet/copernicus/net/connmgr	10.962s	coverage: 88.0% of statements
ok  	github.com/copernet/copernicus/net/limits	1.337s	coverage: 26.3% of statements
# github.com/copernet/copernicus/logic/lundo.test
# github.com/copernet/copernicus/model/block.test
# github.com/copernet/copernicus/logic/ltx.test
# github.com/copernet/copernicus/model.test
# github.com/copernet/copernicus/model/blockindex.test
ok  	github.com/copernet/copernicus/net/server	17.292s	coverage: 72.7% of statements
?   	github.com/copernet/copernicus/net/socks	[no test files]
ok  	github.com/copernet/copernicus/net/syncmanager	13.897s	coverage: 80.8% of statements
?   	github.com/copernet/copernicus/net/upnp	[no test files]
ok  	github.com/copernet/copernicus/net/wire	10.792s	coverage: 87.8% of statements
ok  	github.com/copernet/copernicus/util	14.845s	coverage: 90.8% of statements
?   	github.com/copernet/copernicus/util/algorithm/mapcontainer	[no test files]
ok  	github.com/copernet/copernicus/util/algorithm/mapcontainer/skiplist	4.297s	coverage: 100.0% of statements
ok  	github.com/copernet/copernicus/util/amount	11.421s	coverage: 95.7% of statements
ok  	github.com/copernet/copernicus/util/base58	1.256s	coverage: 100.0% of statements
ok  	github.com/copernet/copernicus/util/bloom	9.533s	coverage: 86.5% of statements
ok  	github.com/copernet/copernicus/util/cashaddr	8.880s	coverage: 80.7% of statements
ok  	github.com/copernet/copernicus/util/wif	9.861s	coverage: 81.0% of statements
# github.com/copernet/copernicus/model/chain.test
ok  	github.com/copernet/copernicus/logic/lblock	19.555s	coverage: 60.5% of statements
ok  	github.com/copernet/copernicus/logic/lblockindex	10.592s	coverage: 84.5% of statements
# github.com/copernet/copernicus/peer.test
ok  	github.com/copernet/copernicus/logic/lchain	14.419s	coverage: 79.1% of statements
# github.com/copernet/copernicus/model/pow.test
ok  	github.com/copernet/copernicus/logic/lmempool	16.248s	coverage: 79.8% of statements
ok  	github.com/copernet/copernicus/logic/lmerkleblock	1.510s	coverage: 84.2% of statements
ok  	github.com/copernet/copernicus/logic/lmerkleroot	2.211s	coverage: 89.2% of statements
ok  	github.com/copernet/copernicus/logic/lreindex	1.446s	coverage: 85.3% of statements
ok  	github.com/copernet/copernicus/logic/lscript	2.888s	coverage: 84.2% of statements
# github.com/copernet/copernicus/model/tx.test
# github.com/copernet/copernicus/model/txout.test
# github.com/copernet/copernicus/model/undo.test
# github.com/copernet/copernicus/model/utxo.test
# github.com/copernet/copernicus/model/versionbits.test
# github.com/copernet/copernicus/service.test
# github.com/copernet/copernicus/service/mining.test
# github.com/copernet/copernicus/persist.test
# github.com/copernet/copernicus/persist/blkdb.test
# github.com/copernet/copernicus/persist/disk.test
# github.com/copernet/copernicus/model/mempool.test
ok  	github.com/copernet/copernicus/logic/ltx	35.545s	coverage: 86.1% of statements
ok  	github.com/copernet/copernicus/logic/lundo	8.759s	coverage: 85.1% of statements
?   	github.com/copernet/copernicus/logic/lwallet	[no test files]
2018/12/06 21:42:19.399 [D]  AddToIndexMap:000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f index height:0
2018/12/06 21:42:19.400 [D]  &{GoVersion:1.9.2 Version:1.0.0 BuildDate:20180428 DataDir:/Users/bj1809120051/Library/Application Support/Bitcoincash Reindex:false Excessiveblocksize:32000000 RPC:{RPCListeners:[127.0.0.1:18334] RPCUser:copernicus RPCPass:doXT3DXgAQCNU0Li0pujQ6zR3Y RPCLimitUser: RPCLimitPass: RPCCert:/Users/bj1809120051/Library/Application Support/Bitcoincash/rpc.cert RPCKey:/Users/bj1809120051/Library/Application Support/Bitcoincash/rpc.key RPCMaxClients:1000 RPCMaxWebsockets:0 RPCMaxConcurrentReqs:0 RPCQuirks:false} Log:{Level:error Module:[mempool utxo bench service] FileName:copernicus} Mempool:{MinFeeRate:0 LimitAncestorCount:50000 LimitAncestorSize:5000 LimitDescendantCount:50000 LimitDescendantSize:5000 MaxPoolSize:300000000 MaxPoolExpiry:336 CheckFrequency:4294967296} P2PNet:{ListenAddrs:[127.0.0.1:18333] MaxPeers:128 TargetOutbound:64 ConnectPeersOnStart:[] DisableBanning:true BanThreshold:100 TestNet:false RegTest:false SimNet:false DisableListen:false BlocksOnly:false BanDuration:86400 Proxy: UserAgentComments:[] DisableDNSSeed:false DisableRPC:false DisableTLS:false Whitelists:[] NoOnion:true Upnp:false ExternalIPs:[] MaxTimeAdjustment:4200} AddrMgr:{SimNet:false ConnectPeers:[]} Protocol:{NoPeerBloomFilters:true DisableCheckpoints:true} Script:{AcceptDataCarrier:true MaxDatacarrierBytes:223 IsBareMultiSigStd:true PromiscuousMempoolFlags: Par:32} TxOut:{DustRelayFee:83} Chain:{AssumeValid: UtxoHashStartHeight:-1 UtxoHashEndHeight:-1} Mining:{BlockMinTxFee:100 BlockMaxSize:2000000 Strategy:ancestorfeerate} PProf:{IP:localhost Port:6060} BlockIndex:{CheckBlockIndex:false} Wallet:{Enable:false Broadcast:false SpendZeroConfChange:true}}
2018/12/06 21:42:19.402 [E]  Can't listen on 127.0.0.1:18333: listen tcp4 127.0.0.1:18333: bind: address already in use
panic: server init fail

goroutine 1 [running]:
github.com/copernet/copernicus/peer_test.initEnv()
	/Users/bj1809120051/.go/src/github.com/copernet/copernicus/peer/peer_test.go:265 +0xb71
github.com/copernet/copernicus/peer_test.TestMain(0xc000125300)
	/Users/bj1809120051/.go/src/github.com/copernet/copernicus/peer/peer_test.go:52 +0x89
main.main()
	_testmain.go:116 +0x32f
FAIL	github.com/copernet/copernicus/peer	10.536s
ok  	github.com/copernet/copernicus/model	9.843s	coverage: 87.2% of statements
ok  	github.com/copernet/copernicus/model/block	8.745s	coverage: 84.8% of statements
ok  	github.com/copernet/copernicus/model/blockindex	56.925s	coverage: 77.9% of statements
ok  	github.com/copernet/copernicus/model/chain	11.324s	coverage: 79.7% of statements
ok  	github.com/copernet/copernicus/model/consensus	7.979s	coverage: 100.0% of statements
ok  	github.com/copernet/copernicus/model/mempool	1.546s	coverage: 83.6% of statements
ok  	github.com/copernet/copernicus/model/opcodes	1.297s	coverage: 90.3% of statements
ok  	github.com/copernet/copernicus/model/outpoint	11.491s	coverage: 100.0% of statements
ok  	github.com/copernet/copernicus/model/pow	11.744s	coverage: 81.5% of statements
ok  	github.com/copernet/copernicus/model/script	1.597s	coverage: 87.4% of statements
ok  	github.com/copernet/copernicus/model/tx	13.628s	coverage: 78.2% of statements
ok  	github.com/copernet/copernicus/model/txin	9.057s	coverage: 100.0% of statements
ok  	github.com/copernet/copernicus/model/txout	3.709s	coverage: 86.7% of statements
ok  	github.com/copernet/copernicus/model/undo	10.272s	coverage: 96.8% of statements
ok  	github.com/copernet/copernicus/model/utxo	2.500s	coverage: 80.2% of statements
ok  	github.com/copernet/copernicus/model/versionbits	1.510s	coverage: 6.7% of statements
?   	github.com/copernet/copernicus/model/wallet	[no test files]
ok  	github.com/copernet/copernicus/log	1.578s	coverage: 97.6% of statements
ok  	github.com/copernet/copernicus/service	12.905s	coverage: 81.7% of statements
ok  	github.com/copernet/copernicus/service/mining	13.191s	coverage: 85.1% of statements
?   	github.com/copernet/copernicus/rpc	[no test files]
ok  	github.com/copernet/copernicus/rpc/btcjson	1.371s	coverage: 99.3% of statements
ok  	github.com/copernet/copernicus/conf	11.770s	coverage: 78.6% of statements
ok  	github.com/copernet/copernicus/persist	1.459s	coverage: 91.7% of statements
ok  	github.com/copernet/copernicus/persist/blkdb	1.464s	coverage: 78.0% of statements
ok  	github.com/copernet/copernicus/persist/db	12.185s	coverage: 84.3% of statements
ok  	github.com/copernet/copernicus/persist/disk	1.681s	coverage: 62.1% of statements
ok  	github.com/copernet/copernicus/errcode	1.514s	coverage: 82.6% of statements
?   	github.com/copernet/copernicus	[no test files]

```

**Comment by whunmr** [comment]
fixed in https://github.com/copernet/copernicus/commit/21150af337c245af821d20502496ca45e54113aa
