### ISSUE TITLE
panic: init CoinsDB failed...resource temporarily unavailable

### ISSUE THREAD

**Issue by jjz** [copernet/copernicus#81]
An error occurred while running the client ：
```
panic: init CoinsDB failed...resource temporarily unavailable

goroutine 1 [running]:
github.com/copernet/copernicus/model/utxo.newCoinsDB(0xc420280340, 0xc420204340)
       copernet/copernicus/model/utxo/coindb.go:132 +0x128
github.com/copernet/copernicus/model/utxo.InitUtxoLruTip(0xc420155e70)
       copernet/copernicus/model/utxo/lrucache.go:30 +0x2e
main.appInitMain(0xc42001e1b0, 0x1, 0x1)
        copernet/copernicus/initmain.go:28 +0x1a1
main.bchMain(0x4785700, 0xc420026140, 0xc42001e1b0, 0x1, 0x1, 0x0, 0x0)
        copernet/copernicus/main.go:37 +0x4b
main.main()
       copernet/copernicus/main.go:101 +0x103

```
The reason is that the client did not close properly ,  The client needs to be monitored and run in the background.

**Comment by whunmr** [comment]
thanks for reporting, this error will occurred when another instance is running.

will close this issue now, please reopen if it happens even not other instance is running.
